sonar.projectKey=amurlaniakea_variant_confidence
sonar.organization=amurlaniakea
sonar.projectName=variant-confidence

sonar.sources=variant_confidence
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=tests/**/*.py,**/__pycache__/**,**/*.pyc
sonar.python.version=3.11,3.12
sonar.python.coverage.reportPaths=coverage.xml
